### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by mosauter** [mosauter/WT_Battleship#1]
- [x] Google Login
- [x] Login name should getted for the socket method
- [x] Game - Username mapped to Google name
- ...

**Comment by mosauter** [comment]
@p1206-htwg @fewieden

**Comment by p1206-htwg** [comment]
Mit SecureSocial für Play 2.4 gibt es Schwierigkeiten. Die offizielle Dokumentation ist in einigen Teilen veraltet, erst bei der Fehlersuche ist das aufgefallen. Das einzige, an das man sich für Play 2.4 orientieren kann, sind die Samples. Diese konnte ich ebenfalls nicht laden, hier kamen dependency Probleme schon beim kompilieren, die ich versucht habe beim offiziellen Sample zu korrigieren (alles mit deren offiziellen sample). Das hat nicht geklappt, aber damit habe ich mich nicht ausführlich beschäftigt. Ich habe bei Herrn Boger auch reingeschaut, einige Fehler konnte ich beseitigen, jedoch hat auch er, wie in der Dokumentation auf das Plugin-System gesetzt, das eben nicht mehr unterstützt wird, diese Fehler kann ich noch nicht bei ihm beseitigen, aber wir werden sie wohl auch haben. Ich versuche jetzt, zu verstehen, wie im Sample (das ebenfalls Fehler hat) das Plugin-System ersetzt wurde. Das sprengt aber noch einmal den Rahmen für die Login-Aufgabe. Ich schau noch ein paar Stunden rein, ansonsten denke ich, wäre es besser zur anderen authenticate-Methode umzuschwenken. Das SecureSocial ist wirklich eine prima Sache, wenn man momentan nicht mit Play 2.4 arbeitet und eine stabile Version nimmt. Dummerweise gibt es eben jetzt ein Refactoring, das noch nicht dokumentiert wurde. Die letzten Änderungen sind auch erst ein paar Tage her.

**Comment by p1206-htwg** [comment]
from localhost:
google-login implemented, facebook-login implemented,
authorizations requests implemented, redirections implemented,
retrieving account-username/email can be switched (implemented),
logout implemented, view implemented and graphically designed

todo:
further improving view (will take elements from implemented chat room)
important: configuration for heroku (difficulties expected)
after that reconfiguration of application settings on google and facebook
refactoring methods (not highest priority at this stage)
reconfiguring routes/redirections
important: dynamic navbar (server-client communication and further methods needed (@fewieden @mosauter , your collaboration needed here) (could also do without, but would be awesome) (the listed links in the footer might be helpful^1)
important: merging with master might cause some problems, because of resetting dependencies and modules (will talk through in exercise lesson)

further remarks:
the current implementation is completely new,
play authenticate and securesocial have both also been implemented (!):
play authenticate: at last stage no compilation errors, however runtime errors that are due to some incompatibilities with play 2.3.4 that haven´t been solved yet by developers
secureSocial: completely worked through documentation and official examples, none of them are functioning due to major refactoring (from 2.3.4 no plugins are used, no documentation exists for that). Still, login and redirecting works thanks to rewriting runtime environment and rewriting methods with help of other external libraries. -> should definitely be shown in presentation
-major problem is that there is no system with compatibility for 2.3.4 even though some claim it. The current version has been working so far, however, it is complex and problems during todo-tasks should be expected.
-the current-user-accounts can be mapped to their messages in chatroom however that would be major overkill at this stage

^1: http://www.pac4j.org/apidocs/pac4j/org/pac4j/core/profile/CommonProfile.html
http://www.pac4j.org/apidocs/pac4j/org/pac4j/core/profile/ProfileManager.html
https://github.com/pac4j/j2e-pac4j
https://github.com/pac4j/vertx-pac4j/issues/55
also: the file "navigation.scala.html" under "views" from "play java silhouette sample" (source:https://github.com/mohiva/play-silhouette-seed)

**Comment by p1206-htwg** [comment]
Das Login ist am Mittag nach den Übungen zusammengekracht, weil doch tatsächlich die pac4j heute morgen geupdated wurde. Die neuen dependencies sind jetzt alle auf dem Branch (pacTest1). Das fb-login sollte jetzt für alle klappen, Anpassungen im Code dann in den nächsten Tagen. Eine aktualisierte Liste der "finalen" Branches und kleine Änderungen kommen demnächst.

**Comment by p1206-htwg** [comment]
die redirect urls sind in den app-konfigurationen (google developer/facebook developer) angepasst worden, internal error besteht weiterhin auf heroku (lokal voll funktionsfähig) (besprechen Mittwoch)

**Comment by p1206-htwg** [comment]
alle alten redirects sind entfernt (es sind nur noch die neuen urls von heroku drin), lokal kommt dennoch eine andere fehlermeldung, als auf heroku. Fehler muss woanders liegen.

**Comment by p1206-htwg** [comment]
durch die Änderung der baseUrl in application.conf von localhost auf mfpbattleship.herokuapp.com..., wird momentan bereits vom localhost nach anmeldung auf heroku umgeleitet, jedoch bleibt dort der internal error immer noch fest verankert, dieser kommt so im localhost überhaupt nicht vor. An den redirects URL-kann das nicht liegen, evtl. verlangt heroku weitere Einstellungen.
-> baseURL wird vorerst wieder auf localhost gesetzt in applicaton.conf

**Comment by p1206-htwg** [comment]
mir ist aufgefallen, dass es unterschiede in der darstellung der game seite (seite, die nach dem login erscheint) gibt zwischen dem master-branch und dem ursprünglichen branch für den login (refactoringandviews), nur als Hinweis für Mittwoch

**Comment by mosauter** [comment]
Ich bin sowieso dabei auf branch fb-clean-pac alles zu refactorn, files zu löschen, redirects zu ändern, Clients raus zu schmeißen, alles ein wenig verständlicher zu machen. 
Mit dem merge warte ich aber noch.
