### ISSUE TITLE
I am ready doesn't work

### ISSUE THREAD

**Issue by rugo** [mosauter/WT_Battleship#23]
:-1:

**Comment by rugo** [comment]
![360_borat_lebanon0109](https://cloud.githubusercontent.com/assets/9132874/12553396/6e97cdb4-c377-11e5-94c2-9749079536a1.jpg)

**Comment by mosauter** [comment]
is caused by clicking on "I'm ready" when you are waiting for an opponent before the real game starts.
"fixed" by 37777adf3545c4ac364be1a213389906245080d5
simply removed the "I'm ready"-Button when the client is waiting for an opponent. So you can only 'be ready' if you have an opponent and placed all ships.
